name: fake-news-detection
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10

  # Core scientific computing
  - numpy=1.24.*
  - pandas=2.0.*
  - scipy=1.10.*

  # Machine Learning
  - scikit-learn=1.3.*
  - xgboost=1.7.*
  - lightgbm=4.0.*

  # NLP Core Libraries
  - spacy=3.6.0
  - nltk=3.8.1
  - gensim=4.3.1


  # Deep Learning (uncomment if needed)
  - pytorch=2.0.*
  # - torchvision=0.15.*
  # - tensorflow=2.13.*

  # Data visualization
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - plotly=5.14.*

  # Jupyter
  - jupyter=1.0.*
  - jupyterlab=4.0.*
  - ipykernel=6.23.*

  # Development tools
  - pytest=7.3.*
  - black=23.3.*
  - flake8=6.0.*
  - pylint=2.17.*

  # Utilities
  - tqdm=4.65.*
  - pyyaml=6.0.*
  - python-dotenv=1.0.*

  # Pip-only packages
  - pip=23.1.*
  - pip:
    - mlflow==2.5.0
    - optuna==3.2.0
    - wandb==0.15.4

